settings_version: 0.0.4
datasets_dir: C:\Users\Baran\AppData\Roaming\Ultralytics\data.yaml
weights_dir: weights
runs_dir: runs
uuid: 6dc952c896ec8e9e57ef64071a64d870b927a3eb51964fdd5005ebbb64bec72d
sync: true
api_key: ""
openai_api_key: ""
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
